# Generated by Django 4.1.6 on 2023-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_pic",
            field=models.ManyToManyField(
                default="https://robohash.org/ghjuygh", to="home.picture"
            ),
        ),
    ]
