# Generated by Django 4.1.6 on 2023-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_userinfo_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_pic",
            field=models.ManyToManyField(to="home.picture"),
        ),
    ]
