# Generated by Django 4.1.6 on 2023-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_userinfo_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(
                default="media/photos/None<django.db.models.fields.AutoField>.svg",
                upload_to="user_images",
            ),
        ),
    ]
