# Generated by Django 4.1.6 on 2023-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_userinfo_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(
                default="media/photos/NasOogIeNw.svg", upload_to="user_images"
            ),
        ),
    ]
