# Generated by Django 4.1.6 on 2023-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_picture_picture_random_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_like",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_random_code",
            field=models.CharField(default="5ncC00MiVK", max_length=20),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(
                default="media/photos/m3yKSADetX.svg", upload_to="user_images"
            ),
        ),
    ]
